#!/bin/bash

# TG VPN App - Скрипт быстрой настройки Bybit

echo "🚀 Быстрая настройка Bybit Integration для TG VPN App"
echo ""
echo "📝 Шаги настройки:"
echo ""
echo "1️⃣  Перейди на https://www.bybit.com и авторизуйся"
echo ""
echo "2️⃣  Account Settings → API Management"
echo ""
echo "3️⃣  Нажми 'Create New Key'"
echo ""
echo "4️⃣  Выбери разрешения:"
echo "   - ✅ Read (для Payment API)"
echo "   - ✅ Submit (для создания заказов)"
echo ""
echo "5️⃣  Скопируй API Key и API Secret"
echo ""
echo "6️⃣  Открой .env файл и заполни:"
echo ""
echo "   BYBIT_API_KEY=твой_api_key_здесь"
echo "   BYBIT_API_SECRET=твой_api_secret_здесь"
echo "   BYBIT_WEBHOOK_SECRET=твой_webhook_secret"
echo ""
echo "7️⃣  Для тестирования оставь BYBIT_USE_SANDBOX=true"
echo ""
echo "8️⃣  Для production измени на BYBIT_USE_SANDBOX=false"
echo ""
echo "✅ Готово! Запусти: npm start"
echo ""
echo "📚 Больше информации в BYBIT_SETUP.md"
